import {
    Button,
    VerticalBox,
    HorizontalBox,
    StandardButton,
    TextEdit,
} from "std-widgets.slint";
import { CalcButton } from "components/button.slint";


export component AppWindow inherits Window {
    title: "Calculator";
    min-width: 500px;
    max-width: 500px;
    min-height: 600px;
    max-height: 600px;
    icon: @image-url("../assets/logo.png");
    background: #1e1e1ef3;

    in-out property <string> calc: "0";
    callback add-character(string);
    callback clean();
    callback calculate();
    callback delete();

    VerticalLayout {
        alignment: end;
        spacing: 0px;
        padding: 0px;
        height: parent.height;
        width: parent.width;

        HorizontalBox {
            alignment: end;
            width: parent.width;
            TextInput {
                text: calc;
                font-size: 48px;
                horizontal-alignment: right;
                vertical-alignment: center;
            }
        }

        GridLayout {
            spacing: 5px;
            padding: 5px;
            height: 400px;

            CalcButton {
                bg_color: #303030;
                text: "C";
                clicked => {
                    root.clean();
                }
            }

            CalcButton {
                bg_color: #303030;
                text: "⌫";
                text_size: 48px;
                text_weight: 300;
                clicked => {
                    root.delete();
                }
            }

            CalcButton {
                bg_color: #303030;
                text: "%";
                clicked => {
                    root.add-character("%");
                }
            }

            CalcButton {
                bg_color: #df7b00;
                text: "÷";
                clicked => {
                    root.add-character("÷");
                }
            }

            CalcButton {
                row: 1;
                col: 0;

                bg_color: #3b3b3b;
                text: "7";
                clicked => {
                    root.add-character("7");
                }
            }

            CalcButton {
                row: 1;
                col: 1;
                bg_color: #3b3b3b;
                text: "8";
                clicked => {
                    root.add-character("8");
                }
            }

            CalcButton {
                row: 1;
                col: 2;
                bg_color: #3b3b3b;
                text: "9";
                clicked => {
                    root.add-character("9");
                }
            }

            CalcButton {
                row: 1;
                col: 3;
                bg_color: #df7b00;
                text: "x";
                clicked => {
                    root.add-character("x");
                }
            }

            CalcButton {
                row: 2;
                col: 0;
                bg_color: #3b3b3b;
                text: "4";
                clicked => {
                    root.add-character("4");
                }
            }

            CalcButton {
                row: 2;
                col: 1;

                bg_color: #3b3b3b;
                text: "5";
                clicked => {
                    root.add-character("5");
                }
            }

            CalcButton {
                row: 2;
                col: 2;
                bg_color: #3b3b3b;
                text: "6";
                clicked => {
                    root.add-character("6");
                }
            }

            CalcButton {
                row: 2;
                col: 3;

                bg_color: #df7b00;
                text: "-";
                clicked => {
                    root.add-character("-");
                }
            }

            CalcButton {
                row: 3;
                col: 0;
                bg_color: #3b3b3b;
                text: "1";
                clicked => {
                    root.add-character("1");
                }
            }

            CalcButton {
                row: 3;
                col: 1;
                bg_color: #3b3b3b;
                text: "2";
                clicked => {
                    root.add-character("2");
                }
            }

            CalcButton {
                row: 3;
                col: 2;
                bg_color: #3b3b3b;
                text: "3";
                clicked => {
                    root.add-character("3");
                }
            }

            CalcButton {
                row: 3;
                col: 3;
                bg_color: #df7b00;
                text: "+";
                clicked => {
                    root.add-character("+");
                }
            }

            CalcButton {
                row: 4;
                col: 0;
                colspan: 2;
                bg_color: #3b3b3b;
                text: "0";
                clicked => {
                    root.add-character("0");
                }
            }

            CalcButton {
                row: 4;
                col: 2;
                bg_color: #3b3b3b;
                text: ".";
                clicked => {
                    root.add-character(".");
                }
            }

            CalcButton {
                row: 4;
                col: 3;
                bg_color: #df7b00;
                text: "=";
                clicked => {
                    root.calculate();
                }
            }
        }
    }
}
