import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Calculator";
    min-width: 500px;
    max-width: 500px;
    min-height: 700px;
    max-height: 700px;
    icon: @image-url("../assets/logo.png");
    background: #1e1e1e;
    in-out property <int> counter: 0;
    callback increment-counter();
    callback decrement-counter();
    callback close-window();
    callback minimize-window();

    VerticalBox {
        padding-top: 40px;
        alignment: center;
        Text {
            text: "Bem-vindo ao Slint!";
            font-size: 24px;
            color: white;
            horizontal-alignment: center;
        }

        Text {
            text: "Contador: " + counter;
            font-size: 32px;
            horizontal-alignment: center;
            color: #0066cc;
        }

        HorizontalBox {
            alignment: center;
            spacing: 20px;
            Button {
                text: "➖ Decrementar";
                clicked => {
                    root.decrement-counter();
                }
            }

            Button {
                text: "➕ Incrementar";
                primary: true;
                clicked => {
                    root.increment-counter();
                }
            }
        }
    }
}
